M48
; DRILL file KiCad 10.0.1 date 2026-07-23T20:58:12
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-23T20:58:12+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.5512Y-2.401
X4.7787Y-2.401
T2
X3.859Y-2.45
X5.073Y-3.082
M30
